# print("Hello world")
# print("Assalou alaykum")
# print("mening ismim Suhrob")
# print('men 20 yoshdaman')
# print('men hozirda IT Klasterda oqiyapman')
# print("yana nimadir")
# print("yana nimadir 2")
# print("yana nimadir 3")
# print("yana nimadir 4")
# print("yana nimadir 5")rgba(75, 37, 37, 1)
# print(2+4*2)
# print(19/5)
# print(2**4)
ism=input("ism kiriting: ")
familiya=input("Familiya kiriting: ")
login=input("login kiriting: ")
password=input("password kiriting: ")
print("Assalomu alaykum")
print(f"Welcomr to web site {ism} {familiya}")